sudo: required
language: generic 
services:
  - docker

before_install: 
  - docker build -t muglow1642759/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true muglow1642759/docker-react npm run test