sudo: required
language: generic 
services:
  - docker

before_install: 
  - docker build -t muglow1642759/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true muglow1642759/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-201231068842"
  bucket_path: "docker-react"
  on:
    branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: 
  secure: "$AWS_SECRET_KEY"